merge_queue:
  max_parallel_checks: 1
  queued_label: 'ci:queued'
  dequeued_label: 'ci:dequeued'

queue_rules:
  - name: renovate
    update_method: merge

pull_request_rules:
  - name: label conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict

  - name: Automatic merge for Renovate
    conditions:
      - label=ci:auto-merge
      - base=master
      - check-success=typecheck
    actions:
      queue:
        name: renovate
