---
name: 'changelog-previous-tag'
description: 'get previous tag for changelog'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/trim21/changelog-previous-tag:v1'
inputs:
  version-spec:
    description: "'semver' or 'pep440'"
    default: 'semver'
