name: release

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: "ghcr.io/${{ github.repository }}"

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=v1

      - name: Build Final Docker Image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
